### ISSUE TITLE
#Subtask 3 - Related to the issue #67 . Maps are missing a legend - Ensure that the legend is only displayed when the 'Color by Speed' preference is selected

### ISSUE THREAD

**Issue by msrana25** [rilling/OSMDashboardConcordia#110]
**Is your feature request related to a problem? Please describe.**
Ensure that the legend is only displayed when the 'Color by Speed' preference is selected

**Describe the solution you'd like**
In map.xml present in the root directory **src/main/java/de/storchp/opentracks/osmplugin**. It is essential to ensure that the legend is only displayed when the 'Color by Speed' preference is selected by the user in the app. For other options, such as '**Color by Track**,' the legend layout should be hidden.

**Comment by KhushJani** [comment]
### **_Solution:_**

> This implementation addresses the issue #67 by implementing dynamic legend visibility based on User Preference.

_Overview_

- The proposed solution involved making modifications to the map files located in the root directory 'src/main/java/de/storchp/opentracks/osmplugin'. The primary goal was to conditionally show or hide the legend based on the user's color preference setting.

_Implementation_

- The visibility of the legend is then adjusted based on the user's selected track color mode. If the user has chosen 'Color by Speed', all legend elements are set to be visible; otherwise, the entire legend layout is hidden. 
- This implementation ensures a dynamic and context-aware user interface, displaying the legend only when it is relevant based on the user's color preference.
- Users selecting 'Color by Speed' will now have access to a visual legend, providing additional information about the displayed data on the map.

![Khush](https://github.com/rilling/OSMDashboardConcordia/assets/88198216/e3f11632-ab3d-4f85-80f6-c4bca0b7d3a4)
