### ISSUE TITLE
Adaptability Issue - Class variables has public accessibility in TrackPointsDebug.java (Group 16 - 40276709)

### ISSUE THREAD

**Issue by sannidhi470** [rilling/OSMDashboardConcordia#20]
**Bug Description:**
TrackPointsDebug.java (Line 4,5) has variables which allows public accessibility to the class. This can cause the variables to change afterwards from anywhere in the code and may not meet the programmer’s assumptions. Sonarqube identifies it as a code smell as it leads to unauthorized modifications.

**Expected Behaviour:**
Make the variables static final as it will prevent its values to be modified later. Once the value is assigned to static final variables it can never be changed.

**Screenshots:**

TrackPointsDebug.java file in Sonarqube before the issue was resolved:

![image](https://github.com/rilling/OSMDashboardConcordia/assets/61378821/d7f4cf43-9d24-4a17-94b3-95877d107dcb)

TrackPointsDebug.java file in Sonarqube after resolution:

**Fixed Commit:**
ce936b6cc2c06dd8c54526a8752388f40c03497b

**Comment by shiransilva** [comment]
It is not possible to change these variables to static final since these variables are used and modified in the de.storchp.opentracks.osmplugin.dashboardapi
.TrackPoint.TrackPointsBySegments() method. Once these variables changed to static final, Compiler is throwing errors. 
Please refer the below Screen shots after the changes.

<img width="1511" alt="TrackPointsDebug" src="https://github.com/rilling/OSMDashboardConcordia/assets/29114147/1068ce1d-2de4-4298-8607-58c55252aa48">

<img width="1492" alt="TrackPoint1" src="https://github.com/rilling/OSMDashboardConcordia/assets/29114147/7dcad94b-ac3b-480b-8a4c-07a1cb06c350">

<img width="1496" alt="TrackPoint2" src="https://github.com/rilling/OSMDashboardConcordia/assets/29114147/5dae642f-1e76-4035-b3ea-b050ada3e94d">

Hence it is not possible to resolve this code smell as per the Sonarqube suggestion.
